name: jp_design_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scaled_app: ^2.3.0
  smooth_corner: ^1.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  rive: ^0.13.9
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.1
  sf_symbols: ^0.2.0
  flutter_sficon: ^1.1.2
  toggle_switch: ^2.3.0
  flutter_inner_shadow: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/details/
    - assets/graphics/
    - assets/icons/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
